= Fingerprint Toolbox Proposed Draft 1 of the Biometric iTC Overview
:showtitle:
:toc:
:toclevels: 3
:table-caption: Table
:imagesdir: images
:revnumber: 1.0
:revdate: 2021-04-05
:xrefstyle: full

== Introduction

This is an announcement of a public review period for the current Fingerprint Presentation Attack Detection Toolbox from the BIO-iTC. These documents are focused on providing information about the methodology for performing Presentation Attack Detection. The toolbox is designed as companion documents to the PP-Module and Supporting Document to allow for independent update cycles as new attacks and related tests are developed.

This document will provide information about where to find the documents, how to provide feedback and information about the current status of the documents.

Please email isec-itc-bio-info@ipa.go.jp if there are any questions about the Review process.

The latest status of the Review Period, including the latest copies of any documents, can be found at the https://biometricitc.github.io/[Biometrics Security iTC page].

== Review Status Phase
The documents listed here are in the *Fingerprint Toolbox Proposed Draft* phase.

Publication Date:: April 4, 2021
End of Comment Period:: May 7, 2021

== Repositories for Review

The following are the repositories included in this Fingerprint Toolbox Proposed Draft Period:

.Fingerprint Toolbox Proposed Draft Repository
[[DocTable]]
[cols="1,^1,^1",options="header"]
|===

|Title 
|Link
|New Issue

.^|Fingerprint Toolbox
^.^|https://github.com/biometricITC/Fingerprint-Toolbox[Repository]
|https://github.com/biometricITC/Fingerprint-Toolbox/issues/new[New Fingerprint Issue]

|===

The following are the documents to use in support of the Proposed Draft Period.

.Supporting Documents
[[SupDocTable]]
[cols="1,1",options="header"]
|===
|Title ^|Link

.^|Comment Matrix
^|https://biometricitc.github.io/comment/BIO-iTC-CommentsMatrix.xlsx[Download Comment Matrix]


|===

== Document Release Process
The BIO-iTC follows the document release process below for the publication of the Fingerprint Toolbox. 

[ditaa,timeline,png]
....
                                  
    +----------+   +----------+   +----------+   +----------+   +----------+   +----------+
    |          |   |          |   | Public   |   | cYEL     |   |          |   |          |
    | Internal |   |  Public  |   | Review   |   | Proposed |   | Proposed |   | Final    |
    |  Draft   |-->|  Review  |-->| Draft 1  |-->|  Draft   |-->|  Update  |-->| Document |
    |          |   |  Draft 1 |   | Update   |   |          |   |          |   | Published|
    |          |   |  (45d)   |   | (60d)    |   |  (30d)   |   | (10d)    |   |          |
    +----------+   +----------+   +----------+   +----------+   +----------+   +----------+

....

.Review Timeline
[[timeline]]
|===
|Phase |Time |Description

|Internal Draft
|
|The normal, pre-release process for creating the documents

|Public Review Draft 1
|45 days
|iTC has voted according to Terms of Reference to release this version for public review. Public (i.e. from non-iTC participants) comments are accepted during this period

|Public Review Draft 1 Update
|Up to 60 days
|The iTC will review all received comments and update the documents accordingly

|Public Review Draft 2 (Optional, not shown)
|45 days
|iTC has voted according to Terms of Reference to release this version for public review. Public (i.e. from non-iTC participants) comments are accepted during this period

|Public Review Draft 2 Update (Optional, not shown)
|Up to 60 days
|The iTC will review all received comments and update the documents accordingly

|Proposed Draft
|30 days
|iTC has voted according to Terms of Reference to propose this as the final document. Public (i.e. from non-iTC participants) comments are accepted during this period

|Proposed Update
|10 days
|iTC reviews any further comments and prepares the document for final publishing (updating all dates, producing official versions for publication)

|Final Document Published
|
|Documents are posted to Common Criteria Portal

|===

The iTC may decide, based on the comments received during the Public Review Draft 1 period, that a Public Review Draft 2 period is needed, though the intent is to move to Proposed Draft after this comment period. Public announcement of a proposed draft will be made once all comments have been addressed.

=== Review Process
There are two ways to contribute comments and suggestions to the iTC. The first is through GitHub, the second by spreadsheet. It should be noted however that comments that are received via the spreadsheet will be added to the GitHub repository to allow for a comprehensive discussion. Also, feedback for comments is only provided via the answers in the GitHub comments. 

Each comment should have a suggested resolution proposed if a change is needed to the document.

==== GitHub Review Process
To use GitHub to submit comments, you must have a GitHub account (and it is assumed you know how to use GitHub). Each comment should be submitted as an individual issue with the Label "Public Review" assigned. The link to create a new issue for each individual toolbox can be found in <<DocTable>>. Pull Requests created for any issues will be linked to these Issues for traceability.

==== Comment Matrix Spreadsheet Review Process
In the <<SupDocTable>> table there is a link to the Comment Matrix spreadsheet. There are instructions for using the Matrix on the second worksheet. Please create a separate copy of the spreadsheet for each document.

Email the spreadsheets to isec-itc-bio-info@ipa.go.jp.

=== Additional Notes
The Fingerprint Verification List has known broken links within the file which will be updated during the Public Review Draft 1 Update phase.