= Proposed Draft of the Biometric iTC PP-Module & Supporting Document v2.0 Overview
:showtitle:
:toc:
:toclevels: 3
:table-caption: Table
:revnumber: 1.0
:revdate: 2024-01-07
:xrefstyle: full

== Introduction

This is an announcement of a public review period for the PP-Module and the PP-Module Supporting Document from the BIO-iTC. As the change to the PP-Module and Supporting Document is to add a requirement to better link how PAD is claimed (or not claimed) to accomodate that additional PAD toolboxes that are being created, this change is felt to not need as long a review period before publication. As such the document is immediately being placed into the Proposed Draft stage of review.

This document will provide information about where to find the documents, how to provide feedback and information about the current status of the documents.

Please email px-isec-itc-bio-info@ipa.go.jp if there are any questions about the Review process.

The latest status of the Review Period, including the latest copies of any documents, can be found at the https://biometricitc.github.io/[Biometrics Security iTC page].

== Review Status Phase
The documents listed here are in the v2.0 *Proposed Draft* phase.

Publication Date:: January 7, 2025
End of Comment Period:: February 7, 2025

== Documents for Review

The following are the documents included in this v2.0 Proposed Draft Period:

.Review Documents
[[DocTable]]
[cols="3,^.^1,^.^2",options="header"]
|===
|Title 
|Version 
|Link

|collaborative PP-Module for Mobile biometric enrolment and verification - for unlocking the device - [BIOPP-Module]
|2.0
|https://biometricitc.github.io/v2.0/Proposed-Draft/MOD-BIO-enrl-v2.0-PD.pdf[Download PP-Module]

|Supporting Document Mandatory Technical Document: Evaluation Activities for collaborative PP-Module for Mobile biometric enrolment and verification - for unlocking the device - [BIOSD]
|2.0
|https://biometricitc.github.io/v2.0/Proposed-Draft/SD-BIO-enrl-v2.0-PD.pdf[Download Supporting Document]

|PP-Configuration for Protection Profile for Mobile Device Fundamentals and collaborative PP-Module for Biometric enrolment and verification - for unlocking the device - [CFG-MDF-BIO]
|2.0
|https://biometricitc.github.io/v2.0/Proposed-Draft/CFG-MDF-BIO-v2.0-PD.pdf[Download PP-Configuration]

|GitHub Release Page
|
|https://github.com/biometricITC/cPP-biometrics/releases/tag/2.0PD[v2.0 Proposed Draft]

|===

The following are the documents to use in support of the Proposed Draft Period.

.Supporting Documents
[[SupDocTable]]
[cols="1,1",options="header"]
|===
|Title ^|Link

.^|Comment Matrix
^|https://biometricitc.github.io/comment/BIO-iTC-CommentsMatrix.xlsx[Download Comment Matrix]


|===

== Document Release Process
The BIO-iTC follows the document release process below for the publication of documents. Generally the PP (PP-Module and PP-Configuration) and SD would be released at the same time.

[ditaa]
....

    +----------+   +----------+   +----------+   +-----------+
    |          |   |  cYEL    |   |          |   |           |
    | Internal |   | Proposed |   | Proposed |   | Final     |
    |  Draft   +-->|  Draft   |-->|  Update  |-->| Document  |
    |          |   |          |   |          |   | Published |
    |          |   | (30d)    |   | (10d)    |   |           |
    +----------+   +----------+   +----------+   +-----------+
....

.Review Timeline
[[timeline]]
[cols=".^2,.^1,3",options="header"]
|===

|Phase 
|Time 
|Description

|Internal Draft
|
|The normal, pre-release process for creating the documents

|Proposed Draft
|30 days
|iTC has voted according to Terms of Reference to propose this as the final document. Public (i.e. from non-iTC participants) comments are accepted during this period

|Proposed Update
|10 days
|iTC reviews any further comments and prepares the document for final publishing (updating all dates, producing official versions for publication)

|Final Document Published
|
|Documents are posted to Common Criteria Portal

|===

=== Review Process
There are two ways to contribute comments and suggestions to the iTC. The first is through GitHub, the second by spreadsheet. It should be noted however that comments that are received via the spreadsheet will be added to the GitHub platform to allow for a comprehensive discussion. Also, feedback for comments is only provided via the answers in the GitHub comments. 

Each comment should have a suggested resolution be proposed if a change is needed to the document.

==== GitHub Review Process
To use GitHub to submit comments, you must have a GitHub account (and it is assumed you know how to use GitHub). Each comment should be submitted as an individual https://github.com/biometricITC/cPP-biometrics/issues[Issue] with the Label "Public Review" assigned. Pull Requests created for any issues will be linked to these Issues for traceability.

==== Comment Matrix Spreadsheet Review Process
In the <<SupDocTable>> table there is a link to the Comment Matrix spreadsheet. There are instructions for using the Matrix on the second worksheet. Please create a separate copy of the spreadsheet for each document.

Email the spreadsheets to px-isec-itc-bio-info@ipa.go.jp.

== Additional Notes
The current documents all have v1.2 listed internally. This will be changed to v2.0 at the final publication along with the final publication date being updated across all the documents.