= Public Review Draft 1 of the Biometric iTC PP-Module & Supporting Document v1.1 Overview
:showtitle:
:toc:
:toclevels: 3
:table-caption: Table
:revnumber: 1.0
:revdate: 2021-07-01
:xrefstyle: full

== Introduction

This is an announcement of a public review period for the PP-Module and PP-Module Supporting Document from the BIO-iTC. By design these documents do not provide information about the methodology for performing Presentation Attack Detection. These are being handled as a toolkit which can be updated separately (and ideally more rapidly) without needing changes to the PP-Module and Supporting Document.

This document will provide information about where to find the documents, how to provide feedback and information about the current status of the documents.

Please email isec-itc-bio-info@ipa.go.jp if there are any questions about the Review process.

The latest status of the Review Period, including the latest copies of any documents, can be found at the https://biometricitc.github.io/[Biometrics Security iTC page].

== Review Status Phase
The documents listed here are in the v1.1 *Public Review Draft 1* phase.

Publication Date:: July 1, 2021
End of Comment Period:: August  15, 2021

== Documents for Review

The following are the documents included in this v1.1 Public Review Draft 1 Period:

.Review Documents
[[DocTable]]
[cols="3,1,2",options="header"]
|===
|Title 
^|Version 
^|Link

|collaborative PP-Module for Mobile biometric enrolment and verification - for unlocking the device -
^.^|1.1
^.^|https://biometricitc.github.io/v1.1/pr-draft1/MOD-BIO-enrl-v1.1DRAFT.pdf[Download PP-Module]

|PP-Configuration for Protection Profile for Mobile Device Fundamentals and collaborative Protection Profile Module for Mobile biometric enrolment and verification - for unlocking the device -
^.^|1.1
^.^|https://biometricitc.github.io/v1.1/pr-draft1/PPC+MDF+BIO-v1.1DRAFT.pdf[Download PP-Configuration]

|Supporting Document Mandatory Technical Document: Evaluation Activities for collaborative PP-Module for Mobile biometric enrolment and verification - for unlocking the device -
^.^|1.1
^.^|https://biometricitc.github.io/v1.1/pr-draft1/SD-BIO-enrl-v1.1DRAFT.pdf[Download Supporting Document]

|===

The following are the documents to use in support of the Public Review Draft 1 Period.

.Supporting Documents
[[SupDocTable]]
[cols="1,1",options="header"]
|===
|Title ^|Link

.^|Comment Matrix
^|https://biometricitc.github.io/comment/BIO-iTC-CommentsMatrix.xlsx[Download Comment Matrix]


|===

== Document Release Process
The BIO-iTC follows the document release process below for the publication of documents. Generally the PP (PP-Module and PP-Configuration) and SD would be released at the same time.

[ditaa]
....
                                  
    +----------+    +----------+   +----------+   +----------+   +----------+
    |          |    |  cYEL    |   | Public   |   |          |   | Public   |
    | Internal |    |  Public  |   | Review   |   |  Public  |   | Review   |
    |  Draft   |--> |  Review  |-->| Draft 1  |-->|  Review  |-->| Draft 2  |-+
    |          |    |  Draft 1 |   | Update   |   |  Draft 2 |   | Update   | |
    |          |    |  (45d)   |   | (60d)    |   |  (45d)   |   | (60d)    | |
    +----------+    +----------+   +----------+   +----------+   +----------+ |
                                                                              |
            +-----------------------------------------------------------------+
            |   +----------+   +----------+   +-----------+
            |   |          |   |          |   |           |
            |   | Proposed |   | Proposed |   | Final     |
            +-->|  Draft   |-->|  Update  |-->| Document  |
                |          |   |          |   | Published |
                | (30d)    |   | (10d)    |   |           |
                +----------+   +----------+   +-----------+
....

.Review Timeline
[[timeline]]
[cols=".^2,.^1,3",options="header"]
|===

|Phase 
|Time 
|Description

|Internal Draft
|
|The normal, pre-release process for creating the documents

|Public Review Draft 1
|45 days
|iTC has voted according to Terms of Reference to release this version for public review. Public (i.e. from non-iTC participants) comments are accepted during this period

|Public Review Draft 1 Update
|Up to 60 days
|The iTC will review all received comments and update the documents accordingly

|Public Review Draft 2
|45 days
|iTC has voted according to Terms of Reference to release this version for public review. Public (i.e. from non-iTC participants) comments are accepted during this period

PAD Toolbox drafts will be published with this review (final review on toolboxes may proceed independently from rest of documents).

|Public Review Draft 2 Update
|Up to 60 days
|The iTC will review all received comments and update the documents accordingly

|Public Review Draft 3 (Optional, not shown)
|45 days
|iTC has voted according to Terms of Reference to release this version for public review. Public (i.e. from non-iTC participants) comments are accepted during this period

|Public Review Draft 3 Update (Optional, not shown)
|Up to 60 days
|The iTC will review all received comments and update the documents accordingly

|Proposed Draft
|30 days
|iTC has voted according to Terms of Reference to propose this as the final document. Public (i.e. from non-iTC participants) comments are accepted during this period

|Proposed Update
|10 days
|iTC reviews any further comments and prepares the document for final publishing (updating all dates, producing official versions for publication)

|Final Document Published
|
|Documents are posted to Common Criteria Portal

|===

The iTC may decide, based on the comments received during the Public Review Draft 1 period, that a Public Review Draft 2 period is needed. Public announcement of a second review draft or a proposed draft will be made once all comments have been addressed.

=== Review Process
There are two ways to contribute comments and suggestions to the iTC. The first is through GitHub, the second by spreadsheet. It should be noted however that comments that are received via the spreadsheet will be added to the GitHub platform to allow for a comprehensive discussion. Also, feedback for comments is only provided via the answers in the GitHub comments. 

Each comment should have a suggested resolution be proposed if a change is needed to the document.

==== GitHub Review Process
To use GitHub to submit comments, you must have a GitHub account (and it is assumed you know how to use GitHub). Each comment should be submitted as an individual https://github.com/biometricITC/cPP-biometrics/issues[Issue] with the Label "Public Review" assigned. Pull Requests created for any issues will be linked to these Issues for traceability.

==== Comment Matrix Spreadsheet Review Process
In the <<SupDocTable>> table there is a link to the Comment Matrix spreadsheet. There are instructions for using the Matrix on the second worksheet. Please create a separate copy of the spreadsheet for each document.

Email the spreadsheets to isec-itc-bio-info@ipa.go.jp.

== Additional Notes
Among all the changes made to the documents, there are three particular areas where the BIO-iTC is asking for specific review and comments. These areas are noted below.

=== Addition of IAPAR for FIA_MBV_EXT.3
The FIA_MBV_EXT.3 requirement has been updated to include Imposter Attack Presentation Accept Rate (IAPAR) to enhance the specific requirements around presentation attack. There are several questions about this addition the BIO-iTC is looking for feedback on.

* Is the maximum value of 15% (the worst failure rate) an acceptable limit?
* Is there a different rate that would be preferred (one concern is that the requirements are for a whole system and not components, so any measure should be targeted to the whole system)?
* Is there a similar rate that would be preferred for use with enrolment? IAPAR is not valid for enrolment, and the BIO-iTC was unaware of any other measure for the enrolment process.

=== FPT_BDP_EXT.1 Evaluation Activities for ATE_IND.1
The PP-Module has been updated to better integrate with the PP_MD (Mobile Device Fundamenmtals), and the FPT_BDP_EXT.* requirements have all be adjusted. The remaining requirement is targeted to ensuring that biometric data is not sent through the main OS on the device. The current ATE_IND.1 testing strategy is written with the FCS_CKM.1 test activities in mind, where memory is dumped during the biometric capture process to check that the capture isn't accessible to the main OS itself. 

The BIO-iTC is looking for comments about the best method for performing this type of test, or even if this should be proposed as a test strategy. An alternative approach that has been discussed is leaving this as a documentation review where the vendor would provide an architecture description of how the biometric system interacts with the rest of the device (including the main OS).

=== Biometric Sample Quality Assessment
The FIA_MBV_EXT.2 and FIA_MBE_EXT.2 requirements have been updated to point to a specific quality metric, either public (such as ISO 29794-1) or one defined by the developer. While the expectations for meeting a public assessment seem pretty clear (that the report of that review be provided), there are questions about what should be used as the requirements for a developer defined quality assessment.

A concern has been raised that mobile devices (the first target for the BIOPPM) are not normally tested/reviewed against the public quality measures and usually focus on a balance that meets the FAR/FRR needs of the device, and that the public measures are not designed for mobile devices in general, but other systems that may share biometric data.

The BIOSD has a section with a proposed outline of what needs to be provided to the evaluator for review, and is looking for comments on this section to better target it to both what a validator would expect to see as complete and also what a vendor would consider appropriate given the nature of the quality measures.

It is important to note that this information is needed for testing that the samples provided to the biometric system have the information needed to build a template and then to verify a new sample to the template. So the focus is on how to create poor samples and how to ensure they are discarded from use.